name: ETL Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup:
    name: Set Up Environment
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

  extract:
    name: Extract Data
    runs-on: ubuntu-latest
    needs: setup
    timeout-minutes: 10
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install Dependencies and Run Extract
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          python src/etl/extract.py
      - name: Save Extracted Data
        uses: actions/upload-artifact@v3
        with:
          name: raw-data
          path: raw_data.pkl

  transform:
    name: Transform Data
    runs-on: ubuntu-latest
    needs: extract
    timeout-minutes: 5
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Download Extracted Data
        uses: actions/download-artifact@v3
        with:
          name: raw-data
          path: ./  # Root directory
      - name: Install Dependencies and Run Transform
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          python src/etl/transform.py
      - name: Save Transformed Data
        uses: actions/upload-artifact@v3
        with:
          name: cl
